import { pushSchema } from "drizzle-kit/api";
import { drizzle } from "drizzle-orm/node-postgres";
import pg from "pg";
const schemaModule = await import("./shared/schema.ts");
const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL });
const db = drizzle(pool);
const result = await pushSchema(schemaModule, db);
console.log("hasDataLoss:", result.hasDataLoss);
console.log("warnings:", result.warnings.length);
for (const w of result.warnings) console.log("  W:", w);
console.log("statementsToExecute (" + result.statementsToExecute.length + "):");
for (const s of result.statementsToExecute) console.log("  >", s.replace(/\s+/g, " ").slice(0, 280));
console.log("Applying...");
await result.apply();
console.log("Done.");
await pool.end();
